version: '3'
services:
    app:
        image: gotodo
        container_name: devenv
        build:
            args:
                - target=dev
        environment:
            TODO_ENV: dev
            PORT: 8080
        volumes:
            - .:/app
        ports:
            - '18000:8080'
