version: '3.9'
services:
    app:
        image: gotodo
        container_name: devenv
        build:
            args:
                - target=dev
        environment:
            TODO_ENV: dev
            PORT: 8080
            TODO_DB_HOST: todo-db
            TODO_DB_PORT: 3306
            TODO_DB_USER: todo
            TODO_DB_PASSWORD: todo
            TODO_DB_NAME: todo
            TODO_REDIS_HOST: todo
            TODO_REDIS_PORT: 6379
        volumes:
            - .:/app
        ports:
            - '18000:8080'
        depends_on:
            todo-db:
                condition: service_healthy
    todo-db:
        image: mysql:8.0.29
        platform: linux/amd64
        container_name: todo-db
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: todo
            MYSQL_PASSWORD: todo
            MYSQL_DATABASE: todo
        volumes:
            - todo-db-data:/var/lib/myql
            - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d
        ports:
            - '33306:3306'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            start_period: 1m
            interval: 10s
            timeout: 5s
            retries: 3
    todo-redis:
        image: 'redis:latest'
        container_name: todo-redis
        ports:
            - '36379:6379'
        volumes:
            - todo-redis-data:/data
volumes:
    todo-db-data:
    todo-redis-data:
